//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Web {
    
    
    public partial class GiamSat {
        
        /// <summary>
        /// VdcButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Interface.VdcButton VdcButton1;
        
        /// <summary>
        /// Grid1ExcelDeletedIds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField Grid1ExcelDeletedIds;
        
        /// <summary>
        /// Grid1ExcelData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField Grid1ExcelData;
        
        /// <summary>
        /// CallbackPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VdcInc.CallbackPanel CallbackPanel1;
        
        /// <summary>
        /// Grid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.Grid Grid1;
        
        /// <summary>
        /// ReadOnlyTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate ReadOnlyTemplate;
        
        /// <summary>
        /// MultiLineTextBoxEditTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate MultiLineTextBoxEditTemplate;
        
        /// <summary>
        /// ComboBoxEditTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate ComboBoxEditTemplate;
        
        /// <summary>
        /// Grid2ExcelDeletedIds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField Grid2ExcelDeletedIds;
        
        /// <summary>
        /// Grid2ExcelData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField Grid2ExcelData;
        
        /// <summary>
        /// Grid2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.Grid Grid2;
        
        /// <summary>
        /// ReadOnlyTemplateGrid2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate ReadOnlyTemplateGrid2;
        
        /// <summary>
        /// MultiLineTextBoxEditTemplateGrid2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate MultiLineTextBoxEditTemplateGrid2;
        
        /// <summary>
        /// ComboBoxEditTemplateGrid2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate ComboBoxEditTemplateGrid2;
        
        /// <summary>
        /// Grid3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.Grid Grid3;
        
        /// <summary>
        /// MultiLineTextBoxEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Interface.VdcTextBox MultiLineTextBoxEditor;
        
        /// <summary>
        /// ComboBoxEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.ComboBox.ComboBox ComboBoxEditor;
        
        /// <summary>
        /// ComboBoxEditor1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.ComboBox.ComboBox ComboBoxEditor1;
    }
}
