//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Web {
    
    
    public partial class GiamSat1 {
        
        /// <summary>
        /// ddlNamKeHoach control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Interface.VdcDropDownList ddlNamKeHoach;
        
        /// <summary>
        /// btCapNhatKHV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Interface.VdcButton btCapNhatKHV;
        
        /// <summary>
        /// gridNamKeHoachExcelDeletedIds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField gridNamKeHoachExcelDeletedIds;
        
        /// <summary>
        /// gridNamKeHoachExcelData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField gridNamKeHoachExcelData;
        
        /// <summary>
        /// CallbackPanel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VdcInc.CallbackPanel CallbackPanel2;
        
        /// <summary>
        /// gridNamKeHoach control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.Grid gridNamKeHoach;
        
        /// <summary>
        /// ReadOnlyTemplateGrid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate ReadOnlyTemplateGrid1;
        
        /// <summary>
        /// MultiLineTextBoxEditTemplateGrid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate MultiLineTextBoxEditTemplateGrid1;
        
        /// <summary>
        /// ComboBoxEditTemplateGrid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate ComboBoxEditTemplateGrid1;
        
        /// <summary>
        /// btCapNhatNhaThau control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Interface.VdcButton btCapNhatNhaThau;
        
        /// <summary>
        /// gridNhaThauExcelDeletedIds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField gridNhaThauExcelDeletedIds;
        
        /// <summary>
        /// gridNhaThauExcelData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField gridNhaThauExcelData;
        
        /// <summary>
        /// gridNhaThau control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.Grid gridNhaThau;
        
        /// <summary>
        /// LinkTenGoiThau control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate LinkTenGoiThau;
        
        /// <summary>
        /// ReadOnlyTemplateGrid2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate ReadOnlyTemplateGrid2;
        
        /// <summary>
        /// MultiLineTextBoxEditTemplateGrid2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate MultiLineTextBoxEditTemplateGrid2;
        
        /// <summary>
        /// ComboBoxEditTemplateGrid2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate ComboBoxEditTemplateGrid2;
        
        /// <summary>
        /// btCapNhatHopDong control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Interface.VdcButton btCapNhatHopDong;
        
        /// <summary>
        /// gridHopDongExcelDeletedIds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField gridHopDongExcelDeletedIds;
        
        /// <summary>
        /// gridHopDongExcelData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField gridHopDongExcelData;
        
        /// <summary>
        /// gridHopDong control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.Grid gridHopDong;
        
        /// <summary>
        /// ReadOnlyTemplateGrid3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate ReadOnlyTemplateGrid3;
        
        /// <summary>
        /// MultiLineTextBoxEditTemplateGrid3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate MultiLineTextBoxEditTemplateGrid3;
        
        /// <summary>
        /// ComboBoxEditTemplateGrid3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.GridTemplate ComboBoxEditTemplateGrid3;
        
        /// <summary>
        /// MultiLineTextBoxEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Interface.VdcTextBox MultiLineTextBoxEditor;
        
        /// <summary>
        /// ComboBoxEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.ComboBox.ComboBox ComboBoxEditor;
    }
}
