//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Web.GiamSatServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeHoachVonModel", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class KeHoachVonModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThongTinMoiThauModel", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class ThongTinMoiThauModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThongTinMoThauModel", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class ThongTinMoThauModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThongTinXetThauModel", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class ThongTinXetThauModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoiThauModel", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class GoiThauModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HopDongModel", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class HopDongModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DuAnShortModel", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class DuAnShortModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdDuAnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitSettingLibrary.LoaiNguonVon LoaiNguonVonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitSettingLibrary.LoaiPhanCap LoaiPhanCapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDonViField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDuAnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLoaiDuAnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NamBatDauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NamKetThucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitSettingLibrary.NhomDuAn NhomDuAnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoQuyetDinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDonViQuanLyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDonViThucHienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDuAnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiDuAnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiNguonVonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiPhanCapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNhomDuAnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TongVonDauTuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdDuAn {
            get {
                return this.IdDuAnField;
            }
            set {
                if ((this.IdDuAnField.Equals(value) != true)) {
                    this.IdDuAnField = value;
                    this.RaisePropertyChanged("IdDuAn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitSettingLibrary.LoaiNguonVon LoaiNguonVon {
            get {
                return this.LoaiNguonVonField;
            }
            set {
                if ((this.LoaiNguonVonField.Equals(value) != true)) {
                    this.LoaiNguonVonField = value;
                    this.RaisePropertyChanged("LoaiNguonVon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitSettingLibrary.LoaiPhanCap LoaiPhanCap {
            get {
                return this.LoaiPhanCapField;
            }
            set {
                if ((this.LoaiPhanCapField.Equals(value) != true)) {
                    this.LoaiPhanCapField = value;
                    this.RaisePropertyChanged("LoaiPhanCap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDonVi {
            get {
                return this.MaDonViField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDonViField, value) != true)) {
                    this.MaDonViField = value;
                    this.RaisePropertyChanged("MaDonVi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDuAn {
            get {
                return this.MaDuAnField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDuAnField, value) != true)) {
                    this.MaDuAnField = value;
                    this.RaisePropertyChanged("MaDuAn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaLoaiDuAn {
            get {
                return this.MaLoaiDuAnField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLoaiDuAnField, value) != true)) {
                    this.MaLoaiDuAnField = value;
                    this.RaisePropertyChanged("MaLoaiDuAn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NamBatDau {
            get {
                return this.NamBatDauField;
            }
            set {
                if ((this.NamBatDauField.Equals(value) != true)) {
                    this.NamBatDauField = value;
                    this.RaisePropertyChanged("NamBatDau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NamKetThuc {
            get {
                return this.NamKetThucField;
            }
            set {
                if ((this.NamKetThucField.Equals(value) != true)) {
                    this.NamKetThucField = value;
                    this.RaisePropertyChanged("NamKetThuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitSettingLibrary.NhomDuAn NhomDuAn {
            get {
                return this.NhomDuAnField;
            }
            set {
                if ((this.NhomDuAnField.Equals(value) != true)) {
                    this.NhomDuAnField = value;
                    this.RaisePropertyChanged("NhomDuAn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoQuyetDinh {
            get {
                return this.SoQuyetDinhField;
            }
            set {
                if ((object.ReferenceEquals(this.SoQuyetDinhField, value) != true)) {
                    this.SoQuyetDinhField = value;
                    this.RaisePropertyChanged("SoQuyetDinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDonViQuanLy {
            get {
                return this.TenDonViQuanLyField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDonViQuanLyField, value) != true)) {
                    this.TenDonViQuanLyField = value;
                    this.RaisePropertyChanged("TenDonViQuanLy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDonViThucHien {
            get {
                return this.TenDonViThucHienField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDonViThucHienField, value) != true)) {
                    this.TenDonViThucHienField = value;
                    this.RaisePropertyChanged("TenDonViThucHien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDuAn {
            get {
                return this.TenDuAnField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDuAnField, value) != true)) {
                    this.TenDuAnField = value;
                    this.RaisePropertyChanged("TenDuAn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoaiDuAn {
            get {
                return this.TenLoaiDuAnField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiDuAnField, value) != true)) {
                    this.TenLoaiDuAnField = value;
                    this.RaisePropertyChanged("TenLoaiDuAn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoaiNguonVon {
            get {
                return this.TenLoaiNguonVonField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiNguonVonField, value) != true)) {
                    this.TenLoaiNguonVonField = value;
                    this.RaisePropertyChanged("TenLoaiNguonVon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoaiPhanCap {
            get {
                return this.TenLoaiPhanCapField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiPhanCapField, value) != true)) {
                    this.TenLoaiPhanCapField = value;
                    this.RaisePropertyChanged("TenLoaiPhanCap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNhomDuAn {
            get {
                return this.TenNhomDuAnField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNhomDuAnField, value) != true)) {
                    this.TenNhomDuAnField = value;
                    this.RaisePropertyChanged("TenNhomDuAn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TongVonDauTu {
            get {
                return this.TongVonDauTuField;
            }
            set {
                if ((this.TongVonDauTuField.Equals(value) != true)) {
                    this.TongVonDauTuField = value;
                    this.RaisePropertyChanged("TongVonDauTu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListDuAnModelGridView", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class ListDuAnModelGridView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IPS.Web.GiamSatServiceReference.DuAnShortModel[] DuAnModelsGridViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IPS.Web.GiamSatServiceReference.DuAnShortModel[] DuAnModelsGridView {
            get {
                return this.DuAnModelsGridViewField;
            }
            set {
                if ((object.ReferenceEquals(this.DuAnModelsGridViewField, value) != true)) {
                    this.DuAnModelsGridViewField = value;
                    this.RaisePropertyChanged("DuAnModelsGridView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalPage {
            get {
                return this.TotalPageField;
            }
            set {
                if ((this.TotalPageField.Equals(value) != true)) {
                    this.TotalPageField = value;
                    this.RaisePropertyChanged("TotalPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeHoachVonShortModel", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class KeHoachVonShortModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GhiChuGiamSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitSettingLibrary.GiaiDoanKHV GiaiDoanKHVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdDuAnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdGiamSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitSettingLibrary.KetQuaGiamSat KetQuaGiamSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDonViField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NamKHVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoQuyetDinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenGiaiDoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKetQuaGiamSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitSettingLibrary.TinhTrangXoa TinhTrangXoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrangThaiThucHienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Dot {
            get {
                return this.DotField;
            }
            set {
                if ((this.DotField.Equals(value) != true)) {
                    this.DotField = value;
                    this.RaisePropertyChanged("Dot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GhiChuGiamSat {
            get {
                return this.GhiChuGiamSatField;
            }
            set {
                if ((object.ReferenceEquals(this.GhiChuGiamSatField, value) != true)) {
                    this.GhiChuGiamSatField = value;
                    this.RaisePropertyChanged("GhiChuGiamSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitSettingLibrary.GiaiDoanKHV GiaiDoanKHV {
            get {
                return this.GiaiDoanKHVField;
            }
            set {
                if ((this.GiaiDoanKHVField.Equals(value) != true)) {
                    this.GiaiDoanKHVField = value;
                    this.RaisePropertyChanged("GiaiDoanKHV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdDuAn {
            get {
                return this.IdDuAnField;
            }
            set {
                if ((this.IdDuAnField.Equals(value) != true)) {
                    this.IdDuAnField = value;
                    this.RaisePropertyChanged("IdDuAn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdGiamSat {
            get {
                return this.IdGiamSatField;
            }
            set {
                if ((this.IdGiamSatField.Equals(value) != true)) {
                    this.IdGiamSatField = value;
                    this.RaisePropertyChanged("IdGiamSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitSettingLibrary.KetQuaGiamSat KetQuaGiamSat {
            get {
                return this.KetQuaGiamSatField;
            }
            set {
                if ((this.KetQuaGiamSatField.Equals(value) != true)) {
                    this.KetQuaGiamSatField = value;
                    this.RaisePropertyChanged("KetQuaGiamSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDonVi {
            get {
                return this.MaDonViField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDonViField, value) != true)) {
                    this.MaDonViField = value;
                    this.RaisePropertyChanged("MaDonVi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NamKHV {
            get {
                return this.NamKHVField;
            }
            set {
                if ((this.NamKHVField.Equals(value) != true)) {
                    this.NamKHVField = value;
                    this.RaisePropertyChanged("NamKHV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoQuyetDinh {
            get {
                return this.SoQuyetDinhField;
            }
            set {
                if ((object.ReferenceEquals(this.SoQuyetDinhField, value) != true)) {
                    this.SoQuyetDinhField = value;
                    this.RaisePropertyChanged("SoQuyetDinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenGiaiDoan {
            get {
                return this.TenGiaiDoanField;
            }
            set {
                if ((object.ReferenceEquals(this.TenGiaiDoanField, value) != true)) {
                    this.TenGiaiDoanField = value;
                    this.RaisePropertyChanged("TenGiaiDoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenKetQuaGiamSat {
            get {
                return this.TenKetQuaGiamSatField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKetQuaGiamSatField, value) != true)) {
                    this.TenKetQuaGiamSatField = value;
                    this.RaisePropertyChanged("TenKetQuaGiamSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitSettingLibrary.TinhTrangXoa TinhTrangXoa {
            get {
                return this.TinhTrangXoaField;
            }
            set {
                if ((this.TinhTrangXoaField.Equals(value) != true)) {
                    this.TinhTrangXoaField = value;
                    this.RaisePropertyChanged("TinhTrangXoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrangThaiThucHien {
            get {
                return this.TrangThaiThucHienField;
            }
            set {
                if ((object.ReferenceEquals(this.TrangThaiThucHienField, value) != true)) {
                    this.TrangThaiThucHienField = value;
                    this.RaisePropertyChanged("TrangThaiThucHien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListGoiThauModelGridView", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class ListGoiThauModelGridView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IPS.Web.GiamSatServiceReference.GoiThauShortModel[] GoiThauModelsGridViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IPS.Web.GiamSatServiceReference.GoiThauShortModel[] GoiThauModelsGridView {
            get {
                return this.GoiThauModelsGridViewField;
            }
            set {
                if ((object.ReferenceEquals(this.GoiThauModelsGridViewField, value) != true)) {
                    this.GoiThauModelsGridViewField = value;
                    this.RaisePropertyChanged("GoiThauModelsGridView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalPage {
            get {
                return this.TotalPageField;
            }
            set {
                if ((this.TotalPageField.Equals(value) != true)) {
                    this.TotalPageField = value;
                    this.RaisePropertyChanged("TotalPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoiThauShortModel", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class GoiThauShortModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GhiChuGiamSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitSettingLibrary.GiaiDoanChonNhaThau GiaiDoanDauThauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HinhThucDauThauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdDuAnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdGiamSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdGoiThauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitSettingLibrary.KetQuaGiamSat KetQuaGiamSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDonViField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenGiaiDoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenGoiThauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKetQuaGiamSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitSettingLibrary.TinhTrangXoa TinhTrangXoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrangThaiThucHienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GhiChuGiamSat {
            get {
                return this.GhiChuGiamSatField;
            }
            set {
                if ((object.ReferenceEquals(this.GhiChuGiamSatField, value) != true)) {
                    this.GhiChuGiamSatField = value;
                    this.RaisePropertyChanged("GhiChuGiamSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitSettingLibrary.GiaiDoanChonNhaThau GiaiDoanDauThau {
            get {
                return this.GiaiDoanDauThauField;
            }
            set {
                if ((this.GiaiDoanDauThauField.Equals(value) != true)) {
                    this.GiaiDoanDauThauField = value;
                    this.RaisePropertyChanged("GiaiDoanDauThau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HinhThucDauThau {
            get {
                return this.HinhThucDauThauField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhThucDauThauField, value) != true)) {
                    this.HinhThucDauThauField = value;
                    this.RaisePropertyChanged("HinhThucDauThau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdDuAn {
            get {
                return this.IdDuAnField;
            }
            set {
                if ((this.IdDuAnField.Equals(value) != true)) {
                    this.IdDuAnField = value;
                    this.RaisePropertyChanged("IdDuAn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdGiamSat {
            get {
                return this.IdGiamSatField;
            }
            set {
                if ((this.IdGiamSatField.Equals(value) != true)) {
                    this.IdGiamSatField = value;
                    this.RaisePropertyChanged("IdGiamSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdGoiThau {
            get {
                return this.IdGoiThauField;
            }
            set {
                if ((this.IdGoiThauField.Equals(value) != true)) {
                    this.IdGoiThauField = value;
                    this.RaisePropertyChanged("IdGoiThau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitSettingLibrary.KetQuaGiamSat KetQuaGiamSat {
            get {
                return this.KetQuaGiamSatField;
            }
            set {
                if ((this.KetQuaGiamSatField.Equals(value) != true)) {
                    this.KetQuaGiamSatField = value;
                    this.RaisePropertyChanged("KetQuaGiamSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDonVi {
            get {
                return this.MaDonViField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDonViField, value) != true)) {
                    this.MaDonViField = value;
                    this.RaisePropertyChanged("MaDonVi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenGiaiDoan {
            get {
                return this.TenGiaiDoanField;
            }
            set {
                if ((object.ReferenceEquals(this.TenGiaiDoanField, value) != true)) {
                    this.TenGiaiDoanField = value;
                    this.RaisePropertyChanged("TenGiaiDoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenGoiThau {
            get {
                return this.TenGoiThauField;
            }
            set {
                if ((object.ReferenceEquals(this.TenGoiThauField, value) != true)) {
                    this.TenGoiThauField = value;
                    this.RaisePropertyChanged("TenGoiThau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenKetQuaGiamSat {
            get {
                return this.TenKetQuaGiamSatField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKetQuaGiamSatField, value) != true)) {
                    this.TenKetQuaGiamSatField = value;
                    this.RaisePropertyChanged("TenKetQuaGiamSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitSettingLibrary.TinhTrangXoa TinhTrangXoa {
            get {
                return this.TinhTrangXoaField;
            }
            set {
                if ((this.TinhTrangXoaField.Equals(value) != true)) {
                    this.TinhTrangXoaField = value;
                    this.RaisePropertyChanged("TinhTrangXoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrangThaiThucHien {
            get {
                return this.TrangThaiThucHienField;
            }
            set {
                if ((object.ReferenceEquals(this.TrangThaiThucHienField, value) != true)) {
                    this.TrangThaiThucHienField = value;
                    this.RaisePropertyChanged("TrangThaiThucHien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListHopDongModelGridView", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class ListHopDongModelGridView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IPS.Web.GiamSatServiceReference.HopDongShortModel[] HopDongModelsGridViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IPS.Web.GiamSatServiceReference.HopDongShortModel[] HopDongModelsGridView {
            get {
                return this.HopDongModelsGridViewField;
            }
            set {
                if ((object.ReferenceEquals(this.HopDongModelsGridViewField, value) != true)) {
                    this.HopDongModelsGridViewField = value;
                    this.RaisePropertyChanged("HopDongModelsGridView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalPage {
            get {
                return this.TotalPageField;
            }
            set {
                if ((this.TotalPageField.Equals(value) != true)) {
                    this.TotalPageField = value;
                    this.RaisePropertyChanged("TotalPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HopDongShortModel", Namespace="http://schemas.datacontract.org/2004/07/BusinessLogic.Models")]
    [System.SerializableAttribute()]
    public partial class HopDongShortModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BenAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BenBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GhiChuGiamSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdGiamSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdGoiThauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdHopDongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitSettingLibrary.KetQuaGiamSat KetQuaGiamSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDonViField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenHopDongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKetQuaGiamSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TienNgoaiTeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TienNoiTeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TinhTrangHopDongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitSettingLibrary.TinhTrangXoa TinhTrangXoaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BenA {
            get {
                return this.BenAField;
            }
            set {
                if ((object.ReferenceEquals(this.BenAField, value) != true)) {
                    this.BenAField = value;
                    this.RaisePropertyChanged("BenA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BenB {
            get {
                return this.BenBField;
            }
            set {
                if ((object.ReferenceEquals(this.BenBField, value) != true)) {
                    this.BenBField = value;
                    this.RaisePropertyChanged("BenB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GhiChuGiamSat {
            get {
                return this.GhiChuGiamSatField;
            }
            set {
                if ((object.ReferenceEquals(this.GhiChuGiamSatField, value) != true)) {
                    this.GhiChuGiamSatField = value;
                    this.RaisePropertyChanged("GhiChuGiamSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdGiamSat {
            get {
                return this.IdGiamSatField;
            }
            set {
                if ((this.IdGiamSatField.Equals(value) != true)) {
                    this.IdGiamSatField = value;
                    this.RaisePropertyChanged("IdGiamSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdGoiThau {
            get {
                return this.IdGoiThauField;
            }
            set {
                if ((this.IdGoiThauField.Equals(value) != true)) {
                    this.IdGoiThauField = value;
                    this.RaisePropertyChanged("IdGoiThau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdHopDong {
            get {
                return this.IdHopDongField;
            }
            set {
                if ((this.IdHopDongField.Equals(value) != true)) {
                    this.IdHopDongField = value;
                    this.RaisePropertyChanged("IdHopDong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitSettingLibrary.KetQuaGiamSat KetQuaGiamSat {
            get {
                return this.KetQuaGiamSatField;
            }
            set {
                if ((this.KetQuaGiamSatField.Equals(value) != true)) {
                    this.KetQuaGiamSatField = value;
                    this.RaisePropertyChanged("KetQuaGiamSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDonVi {
            get {
                return this.MaDonViField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDonViField, value) != true)) {
                    this.MaDonViField = value;
                    this.RaisePropertyChanged("MaDonVi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenHopDong {
            get {
                return this.TenHopDongField;
            }
            set {
                if ((object.ReferenceEquals(this.TenHopDongField, value) != true)) {
                    this.TenHopDongField = value;
                    this.RaisePropertyChanged("TenHopDong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenKetQuaGiamSat {
            get {
                return this.TenKetQuaGiamSatField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKetQuaGiamSatField, value) != true)) {
                    this.TenKetQuaGiamSatField = value;
                    this.RaisePropertyChanged("TenKetQuaGiamSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TienNgoaiTe {
            get {
                return this.TienNgoaiTeField;
            }
            set {
                if ((this.TienNgoaiTeField.Equals(value) != true)) {
                    this.TienNgoaiTeField = value;
                    this.RaisePropertyChanged("TienNgoaiTe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TienNoiTe {
            get {
                return this.TienNoiTeField;
            }
            set {
                if ((this.TienNoiTeField.Equals(value) != true)) {
                    this.TienNoiTeField = value;
                    this.RaisePropertyChanged("TienNoiTe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TinhTrangHopDong {
            get {
                return this.TinhTrangHopDongField;
            }
            set {
                if ((object.ReferenceEquals(this.TinhTrangHopDongField, value) != true)) {
                    this.TinhTrangHopDongField = value;
                    this.RaisePropertyChanged("TinhTrangHopDong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitSettingLibrary.TinhTrangXoa TinhTrangXoa {
            get {
                return this.TinhTrangXoaField;
            }
            set {
                if ((this.TinhTrangXoaField.Equals(value) != true)) {
                    this.TinhTrangXoaField = value;
                    this.RaisePropertyChanged("TinhTrangXoa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
