//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Web.GiamSatServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GiamSatServiceReference.IGiamSatServices")]
    public interface IGiamSatServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietKeHoachVon", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietKeHoachVonResponse")]
        System.Data.DataTable ChiTietKeHoachVon(string maDonVi, long namKHV, long idDuAn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietKeHoachVon", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietKeHoachVonResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ChiTietKeHoachVonAsync(string maDonVi, long namKHV, long idDuAn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietMoiThau", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietMoiThauResponse")]
        System.Data.DataTable ChiTietMoiThau(string maDonVi, long idGoiThau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietMoiThau", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietMoiThauResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ChiTietMoiThauAsync(string maDonVi, long idGoiThau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietMoThau", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietMoThauResponse")]
        System.Data.DataTable ChiTietMoThau(string maDonVi, long idGoiThau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietMoThau", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietMoThauResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ChiTietMoThauAsync(string maDonVi, long idGoiThau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietXetThau", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietXetThauResponse")]
        System.Data.DataTable ChiTietXetThau(string maDonVi, long idGoiThau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietXetThau", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietXetThauResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ChiTietXetThauAsync(string maDonVi, long idGoiThau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietGoiThauReturnString", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietGoiThauReturnStringResponse")]
        string ChiTietGoiThauReturnString(string maDonVi, long idGoiThau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietGoiThauReturnString", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietGoiThauReturnStringResponse")]
        System.Threading.Tasks.Task<string> ChiTietGoiThauReturnStringAsync(string maDonVi, long idGoiThau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietHopDongReturnString", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietHopDongReturnStringResponse")]
        string ChiTietHopDongReturnString(string maDonVi, long idHopDong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietHopDongReturnString", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietHopDongReturnStringResponse")]
        System.Threading.Tasks.Task<string> ChiTietHopDongReturnStringAsync(string maDonVi, long idHopDong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietDuAnReturnString", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietDuAnReturnStringResponse")]
        string ChiTietDuAnReturnString(string maDonVi, long idDuAn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/ChiTietDuAnReturnString", ReplyAction="http://tempuri.org/IGiamSatServices/ChiTietDuAnReturnStringResponse")]
        System.Threading.Tasks.Task<string> ChiTietDuAnReturnStringAsync(string maDonVi, long idDuAn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/TimKiemDuAn", ReplyAction="http://tempuri.org/IGiamSatServices/TimKiemDuAnResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnitSettingLibrary.SearchProjectSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnitSettingLibrary.ChangeResultSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnitSettingLibrary.ChangeResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnitSettingLibrary.GiamSatSetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnitSettingLibrary.GiamSatSetting))]
        object[] TimKiemDuAn(UnitSettingLibrary.SearchProjectSetting searchProjectSetting, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/TimKiemDuAn", ReplyAction="http://tempuri.org/IGiamSatServices/TimKiemDuAnResponse")]
        System.Threading.Tasks.Task<object[]> TimKiemDuAnAsync(UnitSettingLibrary.SearchProjectSetting searchProjectSetting, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/DanhSachDuAn", ReplyAction="http://tempuri.org/IGiamSatServices/DanhSachDuAnResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnitSettingLibrary.SearchProjectSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnitSettingLibrary.ChangeResultSettings))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnitSettingLibrary.ChangeResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnitSettingLibrary.GiamSatSetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UnitSettingLibrary.GiamSatSetting))]
        object[] DanhSachDuAn(int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/DanhSachDuAn", ReplyAction="http://tempuri.org/IGiamSatServices/DanhSachDuAnResponse")]
        System.Threading.Tasks.Task<object[]> DanhSachDuAnAsync(int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/DanhSachGiaiDoanKHVReturnString", ReplyAction="http://tempuri.org/IGiamSatServices/DanhSachGiaiDoanKHVReturnStringResponse")]
        string DanhSachGiaiDoanKHVReturnString(string maDonVi, long idDuAn, long nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/DanhSachGiaiDoanKHVReturnString", ReplyAction="http://tempuri.org/IGiamSatServices/DanhSachGiaiDoanKHVReturnStringResponse")]
        System.Threading.Tasks.Task<string> DanhSachGiaiDoanKHVReturnStringAsync(string maDonVi, long idDuAn, long nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/DanhSachGoiThauReturnString", ReplyAction="http://tempuri.org/IGiamSatServices/DanhSachGoiThauReturnStringResponse")]
        string DanhSachGoiThauReturnString(string maDonVi, long idDuAn, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/DanhSachGoiThauReturnString", ReplyAction="http://tempuri.org/IGiamSatServices/DanhSachGoiThauReturnStringResponse")]
        System.Threading.Tasks.Task<string> DanhSachGoiThauReturnStringAsync(string maDonVi, long idDuAn, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/DanhSachHopDongReturnString", ReplyAction="http://tempuri.org/IGiamSatServices/DanhSachHopDongReturnStringResponse")]
        string DanhSachHopDongReturnString(string maDonVi, long idGoiThau, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/DanhSachHopDongReturnString", ReplyAction="http://tempuri.org/IGiamSatServices/DanhSachHopDongReturnStringResponse")]
        System.Threading.Tasks.Task<string> DanhSachHopDongReturnStringAsync(string maDonVi, long idGoiThau, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/CapNhatLoaiNguonVon", ReplyAction="http://tempuri.org/IGiamSatServices/CapNhatLoaiNguonVonResponse")]
        UnitSettingLibrary.ChangeResultSettings CapNhatLoaiNguonVon(string maDonVi, long idDuAn, long loaiNguonVon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/CapNhatLoaiNguonVon", ReplyAction="http://tempuri.org/IGiamSatServices/CapNhatLoaiNguonVonResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> CapNhatLoaiNguonVonAsync(string maDonVi, long idDuAn, long loaiNguonVon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/GiamSat", ReplyAction="http://tempuri.org/IGiamSatServices/GiamSatResponse")]
        UnitSettingLibrary.ChangeResultSettings GiamSat(long loaiGiamSat, UnitSettingLibrary.GiamSatSetting[] listGiamSat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGiamSatServices/GiamSat", ReplyAction="http://tempuri.org/IGiamSatServices/GiamSatResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> GiamSatAsync(long loaiGiamSat, UnitSettingLibrary.GiamSatSetting[] listGiamSat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGiamSatServicesChannel : IPS.Web.GiamSatServiceReference.IGiamSatServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GiamSatServicesClient : System.ServiceModel.ClientBase<IPS.Web.GiamSatServiceReference.IGiamSatServices>, IPS.Web.GiamSatServiceReference.IGiamSatServices {
        
        public GiamSatServicesClient() {
        }
        
        public GiamSatServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GiamSatServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GiamSatServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GiamSatServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ChiTietKeHoachVon(string maDonVi, long namKHV, long idDuAn) {
            return base.Channel.ChiTietKeHoachVon(maDonVi, namKHV, idDuAn);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ChiTietKeHoachVonAsync(string maDonVi, long namKHV, long idDuAn) {
            return base.Channel.ChiTietKeHoachVonAsync(maDonVi, namKHV, idDuAn);
        }
        
        public System.Data.DataTable ChiTietMoiThau(string maDonVi, long idGoiThau) {
            return base.Channel.ChiTietMoiThau(maDonVi, idGoiThau);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ChiTietMoiThauAsync(string maDonVi, long idGoiThau) {
            return base.Channel.ChiTietMoiThauAsync(maDonVi, idGoiThau);
        }
        
        public System.Data.DataTable ChiTietMoThau(string maDonVi, long idGoiThau) {
            return base.Channel.ChiTietMoThau(maDonVi, idGoiThau);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ChiTietMoThauAsync(string maDonVi, long idGoiThau) {
            return base.Channel.ChiTietMoThauAsync(maDonVi, idGoiThau);
        }
        
        public System.Data.DataTable ChiTietXetThau(string maDonVi, long idGoiThau) {
            return base.Channel.ChiTietXetThau(maDonVi, idGoiThau);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ChiTietXetThauAsync(string maDonVi, long idGoiThau) {
            return base.Channel.ChiTietXetThauAsync(maDonVi, idGoiThau);
        }
        
        public string ChiTietGoiThauReturnString(string maDonVi, long idGoiThau) {
            return base.Channel.ChiTietGoiThauReturnString(maDonVi, idGoiThau);
        }
        
        public System.Threading.Tasks.Task<string> ChiTietGoiThauReturnStringAsync(string maDonVi, long idGoiThau) {
            return base.Channel.ChiTietGoiThauReturnStringAsync(maDonVi, idGoiThau);
        }
        
        public string ChiTietHopDongReturnString(string maDonVi, long idHopDong) {
            return base.Channel.ChiTietHopDongReturnString(maDonVi, idHopDong);
        }
        
        public System.Threading.Tasks.Task<string> ChiTietHopDongReturnStringAsync(string maDonVi, long idHopDong) {
            return base.Channel.ChiTietHopDongReturnStringAsync(maDonVi, idHopDong);
        }
        
        public string ChiTietDuAnReturnString(string maDonVi, long idDuAn) {
            return base.Channel.ChiTietDuAnReturnString(maDonVi, idDuAn);
        }
        
        public System.Threading.Tasks.Task<string> ChiTietDuAnReturnStringAsync(string maDonVi, long idDuAn) {
            return base.Channel.ChiTietDuAnReturnStringAsync(maDonVi, idDuAn);
        }
        
        public object[] TimKiemDuAn(UnitSettingLibrary.SearchProjectSetting searchProjectSetting, int pageIndex) {
            return base.Channel.TimKiemDuAn(searchProjectSetting, pageIndex);
        }
        
        public System.Threading.Tasks.Task<object[]> TimKiemDuAnAsync(UnitSettingLibrary.SearchProjectSetting searchProjectSetting, int pageIndex) {
            return base.Channel.TimKiemDuAnAsync(searchProjectSetting, pageIndex);
        }
        
        public object[] DanhSachDuAn(int pageIndex) {
            return base.Channel.DanhSachDuAn(pageIndex);
        }
        
        public System.Threading.Tasks.Task<object[]> DanhSachDuAnAsync(int pageIndex) {
            return base.Channel.DanhSachDuAnAsync(pageIndex);
        }
        
        public string DanhSachGiaiDoanKHVReturnString(string maDonVi, long idDuAn, long nam) {
            return base.Channel.DanhSachGiaiDoanKHVReturnString(maDonVi, idDuAn, nam);
        }
        
        public System.Threading.Tasks.Task<string> DanhSachGiaiDoanKHVReturnStringAsync(string maDonVi, long idDuAn, long nam) {
            return base.Channel.DanhSachGiaiDoanKHVReturnStringAsync(maDonVi, idDuAn, nam);
        }
        
        public string DanhSachGoiThauReturnString(string maDonVi, long idDuAn, int pageIndex) {
            return base.Channel.DanhSachGoiThauReturnString(maDonVi, idDuAn, pageIndex);
        }
        
        public System.Threading.Tasks.Task<string> DanhSachGoiThauReturnStringAsync(string maDonVi, long idDuAn, int pageIndex) {
            return base.Channel.DanhSachGoiThauReturnStringAsync(maDonVi, idDuAn, pageIndex);
        }
        
        public string DanhSachHopDongReturnString(string maDonVi, long idGoiThau, int pageIndex) {
            return base.Channel.DanhSachHopDongReturnString(maDonVi, idGoiThau, pageIndex);
        }
        
        public System.Threading.Tasks.Task<string> DanhSachHopDongReturnStringAsync(string maDonVi, long idGoiThau, int pageIndex) {
            return base.Channel.DanhSachHopDongReturnStringAsync(maDonVi, idGoiThau, pageIndex);
        }
        
        public UnitSettingLibrary.ChangeResultSettings CapNhatLoaiNguonVon(string maDonVi, long idDuAn, long loaiNguonVon) {
            return base.Channel.CapNhatLoaiNguonVon(maDonVi, idDuAn, loaiNguonVon);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> CapNhatLoaiNguonVonAsync(string maDonVi, long idDuAn, long loaiNguonVon) {
            return base.Channel.CapNhatLoaiNguonVonAsync(maDonVi, idDuAn, loaiNguonVon);
        }
        
        public UnitSettingLibrary.ChangeResultSettings GiamSat(long loaiGiamSat, UnitSettingLibrary.GiamSatSetting[] listGiamSat) {
            return base.Channel.GiamSat(loaiGiamSat, listGiamSat);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> GiamSatAsync(long loaiGiamSat, UnitSettingLibrary.GiamSatSetting[] listGiamSat) {
            return base.Channel.GiamSatAsync(loaiGiamSat, listGiamSat);
        }
    }
}
