//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Web.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserServices")]
    public interface IUserServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/CapNhatNhomNguoiDung", ReplyAction="http://tempuri.org/IUserServices/CapNhatNhomNguoiDungResponse")]
        UnitSettingLibrary.ChangeResultSettings CapNhatNhomNguoiDung(string mdv, string nsd, string pas, UnitSettingLibrary.NhomNguoiDungModel nhomNguoiDung);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/CapNhatNhomNguoiDung", ReplyAction="http://tempuri.org/IUserServices/CapNhatNhomNguoiDungResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> CapNhatNhomNguoiDungAsync(string mdv, string nsd, string pas, UnitSettingLibrary.NhomNguoiDungModel nhomNguoiDung);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/DanhSachNhomNguoiDung", ReplyAction="http://tempuri.org/IUserServices/DanhSachNhomNguoiDungResponse")]
        UnitSettingLibrary.NhomNguoiDungModel[] DanhSachNhomNguoiDung(string mdv, string nsd, string pas, int moduleId, string maDonVi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/DanhSachNhomNguoiDung", ReplyAction="http://tempuri.org/IUserServices/DanhSachNhomNguoiDungResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.NhomNguoiDungModel[]> DanhSachNhomNguoiDungAsync(string mdv, string nsd, string pas, int moduleId, string maDonVi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/ChiTietNhomNguoiDung", ReplyAction="http://tempuri.org/IUserServices/ChiTietNhomNguoiDungResponse")]
        UnitSettingLibrary.NhomNguoiDungModel ChiTietNhomNguoiDung(string mdv, string nsd, string pas, string maDonVi, string maNhom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/ChiTietNhomNguoiDung", ReplyAction="http://tempuri.org/IUserServices/ChiTietNhomNguoiDungResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.NhomNguoiDungModel> ChiTietNhomNguoiDungAsync(string mdv, string nsd, string pas, string maDonVi, string maNhom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/XoaNhomNguoiDung", ReplyAction="http://tempuri.org/IUserServices/XoaNhomNguoiDungResponse")]
        UnitSettingLibrary.ChangeResultSettings XoaNhomNguoiDung(string mdv, string nsd, string pas, string maDonVi, long nhomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/XoaNhomNguoiDung", ReplyAction="http://tempuri.org/IUserServices/XoaNhomNguoiDungResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> XoaNhomNguoiDungAsync(string mdv, string nsd, string pas, string maDonVi, long nhomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/CapNhatNguoiDung", ReplyAction="http://tempuri.org/IUserServices/CapNhatNguoiDungResponse")]
        UnitSettingLibrary.ChangeResultSettings CapNhatNguoiDung(string mdv, string nsd, string pas, UnitSettingLibrary.NguoiDungModel nguoiDung);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/CapNhatNguoiDung", ReplyAction="http://tempuri.org/IUserServices/CapNhatNguoiDungResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> CapNhatNguoiDungAsync(string mdv, string nsd, string pas, UnitSettingLibrary.NguoiDungModel nguoiDung);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/DanhSachNguoiDung", ReplyAction="http://tempuri.org/IUserServices/DanhSachNguoiDungResponse")]
        UnitSettingLibrary.NhomNguoiDungModel[] DanhSachNguoiDung(string mdv, string nsd, string pas, string maDonVi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/DanhSachNguoiDung", ReplyAction="http://tempuri.org/IUserServices/DanhSachNguoiDungResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.NhomNguoiDungModel[]> DanhSachNguoiDungAsync(string mdv, string nsd, string pas, string maDonVi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/ChitietNguoiDung", ReplyAction="http://tempuri.org/IUserServices/ChitietNguoiDungResponse")]
        UnitSettingLibrary.NhomNguoiDungModel[] ChitietNguoiDung(string mdv, string nsd, string pas, string maDonVi, long nguoiDungId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/ChitietNguoiDung", ReplyAction="http://tempuri.org/IUserServices/ChitietNguoiDungResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.NhomNguoiDungModel[]> ChitietNguoiDungAsync(string mdv, string nsd, string pas, string maDonVi, long nguoiDungId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/XoaNguoiDung", ReplyAction="http://tempuri.org/IUserServices/XoaNguoiDungResponse")]
        UnitSettingLibrary.ChangeResultSettings XoaNguoiDung(string mdv, string nsd, string pas, string maDonVi, long nhomNguoiDungId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/XoaNguoiDung", ReplyAction="http://tempuri.org/IUserServices/XoaNguoiDungResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> XoaNguoiDungAsync(string mdv, string nsd, string pas, string maDonVi, long nhomNguoiDungId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/IsExistsUserName", ReplyAction="http://tempuri.org/IUserServices/IsExistsUserNameResponse")]
        UnitSettingLibrary.ChangeResultSettings IsExistsUserName(string maDonVi, string tenNguoiDung);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/IsExistsUserName", ReplyAction="http://tempuri.org/IUserServices/IsExistsUserNameResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> IsExistsUserNameAsync(string maDonVi, string tenNguoiDung);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/IsExistsEmail", ReplyAction="http://tempuri.org/IUserServices/IsExistsEmailResponse")]
        UnitSettingLibrary.ChangeResultSettings IsExistsEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/IsExistsEmail", ReplyAction="http://tempuri.org/IUserServices/IsExistsEmailResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> IsExistsEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/IsExistsUserGroupName", ReplyAction="http://tempuri.org/IUserServices/IsExistsUserGroupNameResponse")]
        UnitSettingLibrary.ChangeResultSettings IsExistsUserGroupName(int moduleId, string maDonVi, string tenNhom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/IsExistsUserGroupName", ReplyAction="http://tempuri.org/IUserServices/IsExistsUserGroupNameResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> IsExistsUserGroupNameAsync(int moduleId, string maDonVi, string tenNhom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/Login", ReplyAction="http://tempuri.org/IUserServices/LoginResponse")]
        UnitSettingLibrary.ChangeResultSettings Login(string maDonVi, string userName, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserServices/Login", ReplyAction="http://tempuri.org/IUserServices/LoginResponse")]
        System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> LoginAsync(string maDonVi, string userName, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServicesChannel : IPS.Web.UserServiceReference.IUserServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServicesClient : System.ServiceModel.ClientBase<IPS.Web.UserServiceReference.IUserServices>, IPS.Web.UserServiceReference.IUserServices {
        
        public UserServicesClient() {
        }
        
        public UserServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnitSettingLibrary.ChangeResultSettings CapNhatNhomNguoiDung(string mdv, string nsd, string pas, UnitSettingLibrary.NhomNguoiDungModel nhomNguoiDung) {
            return base.Channel.CapNhatNhomNguoiDung(mdv, nsd, pas, nhomNguoiDung);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> CapNhatNhomNguoiDungAsync(string mdv, string nsd, string pas, UnitSettingLibrary.NhomNguoiDungModel nhomNguoiDung) {
            return base.Channel.CapNhatNhomNguoiDungAsync(mdv, nsd, pas, nhomNguoiDung);
        }
        
        public UnitSettingLibrary.NhomNguoiDungModel[] DanhSachNhomNguoiDung(string mdv, string nsd, string pas, int moduleId, string maDonVi) {
            return base.Channel.DanhSachNhomNguoiDung(mdv, nsd, pas, moduleId, maDonVi);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.NhomNguoiDungModel[]> DanhSachNhomNguoiDungAsync(string mdv, string nsd, string pas, int moduleId, string maDonVi) {
            return base.Channel.DanhSachNhomNguoiDungAsync(mdv, nsd, pas, moduleId, maDonVi);
        }
        
        public UnitSettingLibrary.NhomNguoiDungModel ChiTietNhomNguoiDung(string mdv, string nsd, string pas, string maDonVi, string maNhom) {
            return base.Channel.ChiTietNhomNguoiDung(mdv, nsd, pas, maDonVi, maNhom);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.NhomNguoiDungModel> ChiTietNhomNguoiDungAsync(string mdv, string nsd, string pas, string maDonVi, string maNhom) {
            return base.Channel.ChiTietNhomNguoiDungAsync(mdv, nsd, pas, maDonVi, maNhom);
        }
        
        public UnitSettingLibrary.ChangeResultSettings XoaNhomNguoiDung(string mdv, string nsd, string pas, string maDonVi, long nhomId) {
            return base.Channel.XoaNhomNguoiDung(mdv, nsd, pas, maDonVi, nhomId);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> XoaNhomNguoiDungAsync(string mdv, string nsd, string pas, string maDonVi, long nhomId) {
            return base.Channel.XoaNhomNguoiDungAsync(mdv, nsd, pas, maDonVi, nhomId);
        }
        
        public UnitSettingLibrary.ChangeResultSettings CapNhatNguoiDung(string mdv, string nsd, string pas, UnitSettingLibrary.NguoiDungModel nguoiDung) {
            return base.Channel.CapNhatNguoiDung(mdv, nsd, pas, nguoiDung);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> CapNhatNguoiDungAsync(string mdv, string nsd, string pas, UnitSettingLibrary.NguoiDungModel nguoiDung) {
            return base.Channel.CapNhatNguoiDungAsync(mdv, nsd, pas, nguoiDung);
        }
        
        public UnitSettingLibrary.NhomNguoiDungModel[] DanhSachNguoiDung(string mdv, string nsd, string pas, string maDonVi) {
            return base.Channel.DanhSachNguoiDung(mdv, nsd, pas, maDonVi);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.NhomNguoiDungModel[]> DanhSachNguoiDungAsync(string mdv, string nsd, string pas, string maDonVi) {
            return base.Channel.DanhSachNguoiDungAsync(mdv, nsd, pas, maDonVi);
        }
        
        public UnitSettingLibrary.NhomNguoiDungModel[] ChitietNguoiDung(string mdv, string nsd, string pas, string maDonVi, long nguoiDungId) {
            return base.Channel.ChitietNguoiDung(mdv, nsd, pas, maDonVi, nguoiDungId);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.NhomNguoiDungModel[]> ChitietNguoiDungAsync(string mdv, string nsd, string pas, string maDonVi, long nguoiDungId) {
            return base.Channel.ChitietNguoiDungAsync(mdv, nsd, pas, maDonVi, nguoiDungId);
        }
        
        public UnitSettingLibrary.ChangeResultSettings XoaNguoiDung(string mdv, string nsd, string pas, string maDonVi, long nhomNguoiDungId) {
            return base.Channel.XoaNguoiDung(mdv, nsd, pas, maDonVi, nhomNguoiDungId);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> XoaNguoiDungAsync(string mdv, string nsd, string pas, string maDonVi, long nhomNguoiDungId) {
            return base.Channel.XoaNguoiDungAsync(mdv, nsd, pas, maDonVi, nhomNguoiDungId);
        }
        
        public UnitSettingLibrary.ChangeResultSettings IsExistsUserName(string maDonVi, string tenNguoiDung) {
            return base.Channel.IsExistsUserName(maDonVi, tenNguoiDung);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> IsExistsUserNameAsync(string maDonVi, string tenNguoiDung) {
            return base.Channel.IsExistsUserNameAsync(maDonVi, tenNguoiDung);
        }
        
        public UnitSettingLibrary.ChangeResultSettings IsExistsEmail(string email) {
            return base.Channel.IsExistsEmail(email);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> IsExistsEmailAsync(string email) {
            return base.Channel.IsExistsEmailAsync(email);
        }
        
        public UnitSettingLibrary.ChangeResultSettings IsExistsUserGroupName(int moduleId, string maDonVi, string tenNhom) {
            return base.Channel.IsExistsUserGroupName(moduleId, maDonVi, tenNhom);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> IsExistsUserGroupNameAsync(int moduleId, string maDonVi, string tenNhom) {
            return base.Channel.IsExistsUserGroupNameAsync(moduleId, maDonVi, tenNhom);
        }
        
        public UnitSettingLibrary.ChangeResultSettings Login(string maDonVi, string userName, string pass) {
            return base.Channel.Login(maDonVi, userName, pass);
        }
        
        public System.Threading.Tasks.Task<UnitSettingLibrary.ChangeResultSettings> LoginAsync(string maDonVi, string userName, string pass) {
            return base.Channel.LoginAsync(maDonVi, userName, pass);
        }
    }
}
