//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Web.Appforms.he_thong {
    
    
    public partial class ht_quanlynhomnguoidung {
        
        /// <summary>
        /// txtMaNhom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Interface.VdcTextBox txtMaNhom;
        
        /// <summary>
        /// txtTenNhom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Interface.VdcTextBox txtTenNhom;
        
        /// <summary>
        /// ddlModule control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Interface.VdcDropDownList ddlModule;
        
        /// <summary>
        /// dllMucDoTruyCap control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Interface.VdcDropDownList dllMucDoTruyCap;
        
        /// <summary>
        /// GRLKe1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.Grid GRLKe1;
        
        /// <summary>
        /// VdcButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Interface.VdcButton VdcButton1;
        
        /// <summary>
        /// VdcButton2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Interface.VdcButton VdcButton2;
        
        /// <summary>
        /// Grid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Vdc.Grid.Grid Grid1;
    }
}
