//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Web.BaoCaoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BaoCaoServiceReference.IBaoCaoServices")]
    public interface IBaoCaoServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoCaoServices/DoWork", ReplyAction="http://tempuri.org/IBaoCaoServices/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoCaoServices/DoWork", ReplyAction="http://tempuri.org/IBaoCaoServices/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBaoCaoServicesChannel : IPS.Web.BaoCaoServiceReference.IBaoCaoServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaoCaoServicesClient : System.ServiceModel.ClientBase<IPS.Web.BaoCaoServiceReference.IBaoCaoServices>, IPS.Web.BaoCaoServiceReference.IBaoCaoServices {
        
        public BaoCaoServicesClient() {
        }
        
        public BaoCaoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaoCaoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaoCaoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaoCaoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
